repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args:
          - --line-length=120
  - repo: https://github.com/PyCQA/prospector
    rev: 1.10.1
    hooks:
      - id: prospector
        additional_dependencies:
          - "prospector[with_everything]"
          # the following are needed to run mypy successfully in the pre-commit virtualenv
          - types-setuptools
          - types-PyYAML
        args:
          - --summary-only
          - --zero-exit
  - repo: local
    hooks:
      - id: pre-commit-django-migrations
        name: Check django migrations
        entry: ./manage.py makemigrations --dry-run --check
        language: system
        types: [python]
        pass_filenames: false
      - id: django-test
        name: django-test
        entry: python manage.py test
        always_run: true
        pass_filenames: false
        language: system
