# Generated by Django 5.0.3 on 2024-03-31 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=20)),
                ("version", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="FairingRecoveryBoat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="LandingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Launch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(verbose_name="Launch Time")),
                ("name", models.IntegerField()),
                ("customer", models.CharField(max_length=200)),
                (
                    "launch_outcome",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "success"),
                            ("FAILURE", "failure"),
                            ("PARTIAL FAILURE", "partial failure"),
                        ],
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Orbit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Pad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("nickname", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Rocket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Support",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Tug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="FairingRecovery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("catch", models.BooleanField()),
                ("recovery", models.BooleanField()),
                ("fairing_lat", models.FloatField()),
                ("fairing_long", models.FloatField()),
                (
                    "boat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booster_tracker.fairingrecoveryboat",
                    ),
                ),
                (
                    "launch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booster_tracker.launch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BoosterAndRecovery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("EXPENDED", "expended"),
                            ("OCEAN_SURFACE", "ocean"),
                            ("DRONE_SHIP", "ASDS"),
                            ("GROUND_PAD", "landing zone"),
                        ],
                        max_length=200,
                    ),
                ),
                ("method_success", models.BooleanField()),
                ("recovery_success", models.BooleanField()),
                ("booster_lat", models.FloatField()),
                ("booster_long", models.FloatField()),
                (
                    "booster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booster_tracker.booster",
                    ),
                ),
                (
                    "landing_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booster_tracker.landingzone",
                    ),
                ),
                (
                    "launch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booster_tracker.launch",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="launch",
            name="orbit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="booster_tracker.orbit"
            ),
        ),
        migrations.AddField(
            model_name="launch",
            name="rocket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="booster_tracker.rocket"
            ),
        ),
        migrations.AddField(
            model_name="booster",
            name="rocket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="booster_tracker.rocket"
            ),
        ),
        migrations.CreateModel(
            name="SecondStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=20)),
                ("version", models.CharField(max_length=20)),
                (
                    "rocket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booster_tracker.rocket",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="launch",
            name="support",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="booster_tracker.support",
            ),
        ),
        migrations.AddField(
            model_name="launch",
            name="tug",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="booster_tracker.tug"
            ),
        ),
    ]
