# Generated by Django 5.0.3 on 2024-03-31 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Boat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TUG", "tug"),
                            ("FAIRING_RECOVERY", "fairing recovery"),
                            ("SUPPORT", "support"),
                        ],
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="booster",
            name="rocket",
        ),
        migrations.AlterModelOptions(
            name="launch",
            options={"verbose_name_plural": "Launches"},
        ),
        migrations.AlterField(
            model_name="fairingrecovery",
            name="boat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="booster_tracker.boat"
            ),
        ),
        migrations.AlterField(
            model_name="launch",
            name="support",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="support",
                to="booster_tracker.boat",
            ),
        ),
        migrations.AlterField(
            model_name="launch",
            name="tug",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tug",
                to="booster_tracker.boat",
            ),
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=20)),
                ("version", models.CharField(max_length=20)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BOOSTER", "booster"),
                            ("SECOND_STAGE", "second stage"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rocket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booster_tracker.rocket",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="boosterandrecovery",
            name="booster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="booster_tracker.stage"
            ),
        ),
        migrations.DeleteModel(
            name="SecondStage",
        ),
        migrations.DeleteModel(
            name="FairingRecoveryBoat",
        ),
        migrations.DeleteModel(
            name="Support",
        ),
        migrations.DeleteModel(
            name="Tug",
        ),
        migrations.DeleteModel(
            name="Booster",
        ),
    ]
