# Generated by Django 5.0.3 on 2024-03-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "booster_tracker",
            "0002_boat_remove_booster_rocket_alter_launch_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="launch",
            options={"ordering": ["-time"], "verbose_name_plural": "Launches"},
        ),
        migrations.AlterField(
            model_name="launch",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
