# Generated by Django 5.0.3 on 2024-03-31 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0003_alter_launch_options_alter_launch_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fairingrecovery",
            name="fairing_lat",
        ),
        migrations.RemoveField(
            model_name="fairingrecovery",
            name="fairing_long",
        ),
        migrations.AddField(
            model_name="fairingrecovery",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fairingrecovery",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="landingzone",
            name="nickname",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fairingrecovery",
            name="boat",
            field=models.ForeignKey(
                limit_choices_to={"type": "FAIRING_RECOVERY"},
                on_delete=django.db.models.deletion.CASCADE,
                to="booster_tracker.boat",
            ),
        ),
        migrations.AlterField(
            model_name="launch",
            name="support",
            field=models.ForeignKey(
                limit_choices_to={"type": "SUPPORT"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="support",
                to="booster_tracker.boat",
            ),
        ),
        migrations.AlterField(
            model_name="launch",
            name="tug",
            field=models.ForeignKey(
                limit_choices_to={"type": "TUG"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tug",
                to="booster_tracker.boat",
            ),
        ),
        migrations.CreateModel(
            name="StageAndRecovery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("EXPENDED", "expended"),
                            ("OCEAN_SURFACE", "ocean"),
                            ("DRONE_SHIP", "ASDS"),
                            ("GROUND_PAD", "landing zone"),
                        ],
                        max_length=200,
                    ),
                ),
                ("method_success", models.BooleanField()),
                ("recovery_success", models.BooleanField()),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "landing_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booster_tracker.landingzone",
                    ),
                ),
                (
                    "launch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booster_tracker.launch",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booster_tracker.stage",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="BoosterAndRecovery",
        ),
    ]
