# Generated by Django 5.0.3 on 2024-04-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0004_remove_fairingrecovery_fairing_lat_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stage",
            old_name="serial_number",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="stage",
            name="type",
            field=models.CharField(
                choices=[
                    ("F9_BOOSTER", "Falcon 9 booster"),
                    ("FH_CENTER", "Falcon Heavy center core"),
                    ("SECOND_STAGE", "second stage"),
                ],
                max_length=20,
            ),
        ),
    ]
