# Generated by Django 5.0.3 on 2024-04-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0005_rename_serial_number_stage_name_alter_stage_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stage",
            name="type",
            field=models.CharField(
                choices=[("BOOSTER", "booster"), ("SECOND_STAGE", "second stage")],
                max_length=20,
            ),
        ),
    ]
