# Generated by Django 5.0.3 on 2024-04-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0006_alter_stage_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="launch",
            name="mass",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
