# Generated by Django 5.0.3 on 2024-04-02 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0007_launch_mass"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="launch",
            name="support",
        ),
        migrations.RemoveField(
            model_name="launch",
            name="tug",
        ),
        migrations.AddField(
            model_name="stageandrecovery",
            name="support",
            field=models.ForeignKey(
                default="",
                limit_choices_to={"type": "SUPPORT"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="support",
                to="booster_tracker.boat",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stageandrecovery",
            name="tug",
            field=models.ForeignKey(
                default="",
                limit_choices_to={"type": "TUG"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tug",
                to="booster_tracker.boat",
            ),
            preserve_default=False,
        ),
    ]
