# Generated by Django 5.0.3 on 2024-04-02 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0008_remove_launch_support_remove_launch_tug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stageandrecovery",
            name="support",
        ),
        migrations.RemoveField(
            model_name="stageandrecovery",
            name="tug",
        ),
        migrations.AlterField(
            model_name="stageandrecovery",
            name="landing_zone",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booster_tracker.landingzone",
            ),
        ),
        migrations.AlterField(
            model_name="stageandrecovery",
            name="method_success",
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name="TugAndSupport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "support",
                    models.ForeignKey(
                        limit_choices_to={"type": "SUPPORT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support",
                        to="booster_tracker.boat",
                    ),
                ),
                (
                    "tug",
                    models.ForeignKey(
                        limit_choices_to={"type": "TUG"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tug",
                        to="booster_tracker.boat",
                    ),
                ),
            ],
        ),
    ]
