# Generated by Django 5.0.3 on 2024-04-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0009_remove_stageandrecovery_support_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fairingrecovery",
            name="flights",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
