# Generated by Django 5.0.3 on 2024-04-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0010_fairingrecovery_flights"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fairingrecovery",
            name="recovery",
            field=models.CharField(max_length=200),
        ),
    ]
