# Generated by Django 5.0.3 on 2024-04-02 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0011_alter_fairingrecovery_recovery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fairingrecovery",
            options={"verbose_name_plural": "Fairing Recoveries"},
        ),
        migrations.AlterModelOptions(
            name="stageandrecovery",
            options={"verbose_name_plural": "Boosters and Recoveries"},
        ),
    ]
