# Generated by Django 5.0.3 on 2024-04-02 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0012_alter_fairingrecovery_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tugandsupport",
            name="launch",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="booster_tracker.launch",
            ),
            preserve_default=False,
        ),
    ]
