# Generated by Django 5.0.3 on 2024-04-02 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0013_tugandsupport_launch"),
    ]

    operations = [
        migrations.AddField(
            model_name="launch",
            name="pad",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="booster_tracker.pad",
            ),
            preserve_default=False,
        ),
    ]
