# Generated by Django 5.0.3 on 2024-04-02 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0015_boatsupport_delete_tugandsupport"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportOnLaunch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "boat",
                    models.ForeignKey(
                        limit_choices_to={"type": "SUPPORT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booster_tracker.boat",
                    ),
                ),
                (
                    "launch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booster_tracker.launch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TugOnLaunch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "boat",
                    models.ForeignKey(
                        limit_choices_to={"type": "TUG"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booster_tracker.boat",
                    ),
                ),
                (
                    "launch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booster_tracker.launch",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="BoatSupport",
        ),
    ]
