# Generated by Django 5.0.3 on 2024-04-02 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0016_supportonlaunch_tugonlaunch_delete_boatsupport"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supportonlaunch",
            options={"verbose_name_plural": "Support ships on launch"},
        ),
        migrations.AlterModelOptions(
            name="tugonlaunch",
            options={"verbose_name_plural": "Tugs on Launch"},
        ),
    ]
