# Generated by Django 5.0.3 on 2024-04-02 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0017_alter_supportonlaunch_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stageandrecovery",
            options={"verbose_name_plural": "Stages and Recoveries"},
        ),
    ]
