# Generated by Django 5.0.3 on 2024-04-05 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0018_alter_stageandrecovery_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dragon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("nickname", models.CharField(max_length=20)),
                ("version", models.CharField(max_length=20)),
                (
                    "type",
                    models.CharField(
                        choices=[("CARGO", "cargo"), ("CREW", "crew")], max_length=20
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DragonOnLaunch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dragon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booster_tracker.dragon",
                    ),
                ),
                (
                    "launch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booster_tracker.launch",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Dragon on launch",
            },
        ),
    ]
