# Generated by Django 5.0.3 on 2024-04-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0019_dragon_dragononlaunch"),
    ]

    operations = [
        migrations.AddField(
            model_name="dragononlaunch",
            name="splashdown_time",
            field=models.DateTimeField(null=True, verbose_name="Splashdown Time"),
        ),
    ]
