# Generated by Django 5.0.3 on 2024-04-05 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0021_alter_stageandrecovery_launch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stageandrecovery",
            name="launch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="booster_tracker.launch"
            ),
        ),
    ]
