# Generated by Django 5.0.3 on 2024-04-08 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0022_alter_stageandrecovery_launch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stageandrecovery",
            name="landing_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booster_tracker.landingzone",
            ),
        ),
    ]
