# Generated by Django 5.0.3 on 2024-04-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0023_alter_stageandrecovery_landing_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="launch",
            name="launch_outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUCCESS", "success"),
                    ("FAILURE", "failure"),
                    ("PARTIAL FAILURE", "partial failure"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
