# Generated by Django 5.0.3 on 2024-04-24 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0024_alter_launch_launch_outcome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stageandrecovery",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booster_tracker.stage",
            ),
        ),
    ]
