# Generated by Django 5.0.3 on 2024-04-24 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0025_alter_stageandrecovery_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fairingrecovery",
            name="boat",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type": "FAIRING_RECOVERY"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booster_tracker.boat",
            ),
        ),
    ]
