# Generated by Django 5.0.3 on 2024-04-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0026_alter_fairingrecovery_boat"),
    ]

    operations = [
        migrations.AddField(
            model_name="stageandrecovery",
            name="method_success_2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUCCESS", "success"),
                    ("FAILURE", "failure"),
                    ("PRECLUDED", "precluded"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
