# Generated by Django 5.0.3 on 2024-04-28 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0027_stageandrecovery_method_success_2"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stageandrecovery",
            options={},
        ),
        migrations.RemoveField(
            model_name="stageandrecovery",
            name="method_success",
        ),
    ]
