# Generated by Django 5.0.3 on 2024-04-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0028_alter_stageandrecovery_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stageandrecovery",
            old_name="method_success_2",
            new_name="method_success",
        ),
    ]
