# Generated by Django 5.0.3 on 2024-05-03 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "booster_tracker",
            "0029_rename_method_success_2_stageandrecovery_method_success",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="dragononlaunch",
            name="dragon",
        ),
        migrations.RemoveField(
            model_name="dragononlaunch",
            name="launch",
        ),
        migrations.AddField(
            model_name="stage",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "active"),
                    ("RETIRED", "retired"),
                    ("EXPENDED", "expended"),
                    ("LOST", "lost"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rocket",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booster_tracker.operator",
            ),
        ),
        migrations.CreateModel(
            name="Spacecraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("nickname", models.CharField(blank=True, max_length=20, null=True)),
                ("version", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("CARGO", "cargo"), ("CREW", "crew")], max_length=20
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booster_tracker.operator",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpacecraftOnLaunch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "splashdown_time",
                    models.DateTimeField(null=True, verbose_name="Splashdown Time"),
                ),
                (
                    "launch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booster_tracker.launch",
                    ),
                ),
                (
                    "spacecraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booster_tracker.spacecraft",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Dragon on launch",
            },
        ),
        migrations.DeleteModel(
            name="Dragon",
        ),
        migrations.DeleteModel(
            name="DragonOnLaunch",
        ),
    ]
