# Generated by Django 5.0.3 on 2024-05-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0030_operator_remove_dragononlaunch_dragon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="stage_photos/"),
        ),
    ]
