# Generated by Django 5.0.3 on 2024-05-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0031_stage_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="launch",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
