# Generated by Django 5.0.3 on 2024-05-09 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0032_alter_launch_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PadUsed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="rocket_pad_photos/"
                    ),
                ),
                (
                    "pad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booster_tracker.pad",
                    ),
                ),
                (
                    "rocket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booster_tracker.rocket",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pads used",
            },
        ),
    ]
