# Generated by Django 5.0.3 on 2024-05-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0033_padused"),
    ]

    operations = [
        migrations.AlterField(
            model_name="padused",
            name="image",
            field=models.ImageField(
                default="rocket_pad_photos/rocket_launch_image.jpg",
                upload_to="rocket_pad_photos/",
            ),
        ),
        migrations.AlterField(
            model_name="stageandrecovery",
            name="method",
            field=models.CharField(
                choices=[
                    ("EXPENDED", "expended"),
                    ("OCEAN_SURFACE", "ocean"),
                    ("DRONE_SHIP", "ASDS"),
                    ("GROUND_PAD", "landing zone"),
                    ("PARACHUTE", "parachute"),
                ],
                max_length=200,
            ),
        ),
    ]
