# Generated by Django 5.0.3 on 2024-05-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0034_alter_padused_image_alter_stageandrecovery_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="pad",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="pad_photos/"),
        ),
        migrations.AddField(
            model_name="pad",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
