# Generated by Django 5.0.3 on 2024-05-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0035_pad_image_pad_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pad",
            name="image",
            field=models.ImageField(
                default="pad_photos/default.png", upload_to="pad_photos/"
            ),
        ),
        migrations.AlterField(
            model_name="pad",
            name="nickname",
            field=models.CharField(max_length=25),
        ),
    ]
