# Generated by Django 5.0.3 on 2024-05-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0036_alter_pad_image_alter_pad_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingzone",
            name="serial_number",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
    ]
