# Generated by Django 5.0.3 on 2024-05-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0037_landingzone_serial_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingzone",
            name="image",
            field=models.ImageField(
                default="pad_photos/default.png", upload_to="landing_zone_photos/"
            ),
        ),
        migrations.AlterField(
            model_name="pad",
            name="image",
            field=models.ImageField(default="default.png", upload_to="pad_photos/"),
        ),
    ]
