# Generated by Django 5.0.3 on 2024-05-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0038_landingzone_image_alter_pad_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingzone",
            name="serial_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
