# Generated by Django 5.0.3 on 2024-05-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0039_alter_landingzone_serial_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingzone",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "active"), ("RETIRED", "retired")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
