# Generated by Django 5.0.3 on 2024-05-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0040_landingzone_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="pad",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "active"), ("RETIRED", "retired")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
