# Generated by Django 5.0.3 on 2024-05-20 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0041_pad_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spacecraft",
            name="operator",
        ),
        migrations.AddField(
            model_name="boat",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "active"), ("RETIRED", "retired")],
                default="ACTIVE",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="rocket",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "active"), ("RETIRED", "retired")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SpacecraftFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "active"), ("RETIRED", "retired")],
                        max_length=200,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booster_tracker.operator",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="spacecraft",
            name="family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booster_tracker.spacecraftfamily",
            ),
        ),
    ]
