# Generated by Django 5.0.3 on 2024-05-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "booster_tracker",
            "0042_remove_spacecraft_operator_boat_status_rocket_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spacecraftfamily",
            options={"verbose_name_plural": "Spacecraft Families"},
        ),
        migrations.AlterField(
            model_name="operator",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="rocket",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name="stage",
            constraint=models.UniqueConstraint(
                fields=("name", "rocket"), name="unique_rocket_stage"
            ),
        ),
    ]
