# Generated by Django 5.0.3 on 2024-05-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "booster_tracker",
            "0043_alter_spacecraftfamily_options_alter_operator_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="landingzone",
            options={"verbose_name_plural": "Landing Zones"},
        ),
        migrations.AlterModelOptions(
            name="padused",
            options={"verbose_name_plural": "Pads Used"},
        ),
        migrations.AlterField(
            model_name="landingzone",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="orbit",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="pad",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="spacecraftfamily",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name="boat",
            constraint=models.UniqueConstraint(
                fields=("name", "type"), name="unique_boat_name_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="spacecraft",
            constraint=models.UniqueConstraint(
                fields=("name", "family"), name="unique_family_name"
            ),
        ),
    ]
