# Generated by Django 5.0.3 on 2024-05-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "booster_tracker",
            "0044_alter_landingzone_options_alter_padused_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spacecraftonlaunch",
            options={"verbose_name_plural": "Dragon on Launch"},
        ),
        migrations.AlterModelOptions(
            name="supportonlaunch",
            options={"verbose_name_plural": "Support Ships on Launch"},
        ),
        migrations.AddConstraint(
            model_name="padused",
            constraint=models.UniqueConstraint(
                fields=("rocket", "pad"), name="unique_rocket_pad"
            ),
        ),
        migrations.AddConstraint(
            model_name="spacecraftonlaunch",
            constraint=models.UniqueConstraint(
                fields=("launch", "spacecraft"), name="unique_launch_spacecraft"
            ),
        ),
        migrations.AddConstraint(
            model_name="stageandrecovery",
            constraint=models.UniqueConstraint(
                fields=("launch", "stage"), name="unique_launch_stage"
            ),
        ),
        migrations.AddConstraint(
            model_name="supportonlaunch",
            constraint=models.UniqueConstraint(
                fields=("launch", "boat"), name="unique_launch_support"
            ),
        ),
        migrations.AddConstraint(
            model_name="tugonlaunch",
            constraint=models.UniqueConstraint(
                fields=("launch", "boat"), name="unique_launch_tug"
            ),
        ),
    ]
