# Generated by Django 5.0.3 on 2024-05-20 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0045_alter_spacecraftonlaunch_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stageandrecovery",
            name="unique_launch_stage",
        ),
    ]
