# Generated by Django 5.0.3 on 2024-05-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0046_remove_stageandrecovery_unique_launch_stage"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="stageandrecovery",
            constraint=models.UniqueConstraint(
                fields=("launch", "stage"), name="unique_launch_stage"
            ),
        ),
    ]
