# Generated by Django 5.0.3 on 2024-05-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0047_stageandrecovery_unique_launch_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="stageandrecovery",
            name="stage_position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MY", "MY"),
                    ("PY", "PY"),
                    ("CENTER", "center"),
                    ("SINGLE_CORE", "single core"),
                ],
                default="SINGLE_CORE",
                max_length=50,
                null=True,
            ),
        ),
    ]
