# Generated by Django 5.0.3 on 2024-05-21 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0048_stageandrecovery_stage_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="spacecraft",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "active"),
                    ("RETIRED", "retired"),
                    ("EXPENDED", "expended"),
                    ("LOST", "lost"),
                ],
                default="ACTIVE",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="spacecraftonlaunch",
            name="recovery_boat",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type": "SPACECRAFT_RECOVERY"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booster_tracker.boat",
            ),
        ),
        migrations.AlterField(
            model_name="boat",
            name="type",
            field=models.CharField(
                choices=[
                    ("TUG", "tug"),
                    ("FAIRING_RECOVERY", "fairing recovery"),
                    ("SUPPORT", "support"),
                    ("SPACECRAFT_RECOVERY", "spacecraft recovery"),
                ],
                max_length=200,
            ),
        ),
    ]
