# Generated by Django 5.0.3 on 2024-05-21 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "booster_tracker",
            "0049_spacecraft_status_spacecraftonlaunch_recovery_boat_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="launch",
            name="orbit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booster_tracker.orbit",
            ),
        ),
    ]
