# Generated by Django 5.0.3 on 2024-05-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0051_alter_stageandrecovery_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stage",
            name="photo",
            field=models.ImageField(
                default="default_booster.jpg", upload_to="stage_photos/"
            ),
        ),
    ]
