# Generated by Django 5.0.3 on 2024-05-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0053_alter_stage_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stage",
            name="photo",
            field=models.ImageField(
                default="media/stage_photos/default_booster.jpg",
                upload_to="stage_photos/",
            ),
        ),
    ]
