# Generated by Django 5.0.3 on 2024-05-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0054_alter_stage_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingzone",
            name="image",
            field=models.ImageField(
                default="media/pad_photos/default.png", upload_to="landing_zone_photos/"
            ),
        ),
        migrations.AlterField(
            model_name="pad",
            name="image",
            field=models.ImageField(
                default="media/pad_photos/default.png", upload_to="pad_photos/"
            ),
        ),
        migrations.AlterField(
            model_name="padused",
            name="image",
            field=models.ImageField(
                default="media/pad_photos/default.png", upload_to="rocket_pad_photos/"
            ),
        ),
    ]
