# Generated by Django 5.0.3 on 2024-05-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0055_alter_landingzone_image_alter_pad_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stage",
            name="photo",
            field=models.ImageField(
                default="stage_photos/default_booster.jpg", upload_to="stage_photos/"
            ),
        ),
    ]
