# Generated by Django 5.0.3 on 2024-05-24 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0056_alter_stage_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stage",
            old_name="photo",
            new_name="image",
        ),
    ]
