# Generated by Django 5.0.3 on 2024-05-24 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0057_rename_photo_stage_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stage",
            name="image",
        ),
    ]
