# Generated by Django 5.0.3 on 2024-05-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0058_remove_stage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="image",
            field=models.ImageField(
                default="stage_photos/default_booster.jpg", upload_to="stage_photos/"
            ),
            preserve_default=False,
        ),
    ]
