# Generated by Django 5.0.3 on 2024-05-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0059_stage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stage",
            name="image",
            field=models.ImageField(
                default="stage_photos/default_booster.jpg", upload_to="stage_photos/"
            ),
        ),
    ]
