# Generated by Django 5.0.3 on 2024-05-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0060_alter_stage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="spacecraft",
            name="image",
            field=models.ImageField(
                default="spacecraft_photos/default_dragon.jpg",
                upload_to="spacecraft_photos/",
            ),
        ),
    ]
