# Generated by Django 5.0.3 on 2024-05-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0061_spacecraft_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spacecraftonlaunch",
            name="splashdown_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Splashdown Time"
            ),
        ),
    ]
