# Generated by Django 5.0.6 on 2024-05-29 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0062_alter_spacecraftonlaunch_splashdown_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rocket",
            name="provider",
        ),
        migrations.AlterField(
            model_name="stageandrecovery",
            name="method",
            field=models.CharField(
                choices=[
                    ("EXPENDED", "expended"),
                    ("OCEAN_SURFACE", "ocean"),
                    ("DRONE_SHIP", "ASDS"),
                    ("GROUND_PAD", "landing zone"),
                    ("PARACHUTE", "parachute"),
                    ("CATCH", "catch"),
                ],
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="RocketFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booster_tracker.operator",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rocket",
            name="family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booster_tracker.rocketfamily",
            ),
        ),
    ]
