# Generated by Django 5.0.6 on 2024-05-30 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "booster_tracker",
            "0063_remove_rocket_provider_alter_stageandrecovery_method_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rocketfamily",
            options={"verbose_name_plural": "Rocket Families"},
        ),
        migrations.AlterField(
            model_name="rocket",
            name="family",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="booster_tracker.rocketfamily",
            ),
        ),
        migrations.AlterField(
            model_name="rocketfamily",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="booster_tracker.operator",
            ),
        ),
    ]
