# Generated by Django 5.0.6 on 2024-06-12 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "booster_tracker",
            "0064_alter_rocketfamily_options_alter_rocket_family_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stageandrecovery",
            options={"verbose_name_plural": "Stage Recoveries"},
        ),
    ]
