# Generated by Django 5.0.6 on 2024-06-24 03:34

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0065_alter_stageandrecovery_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="rocket",
            name="color",
            field=colorfield.fields.ColorField(default="#218243", image_field=None, max_length=25, samples=None),
        ),
    ]
