# Generated by Django 5.0.6 on 2024-07-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0066_rocket_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="orbit",
            name="nickname",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
