# Generated by Django 5.0.6 on 2024-07-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0067_orbit_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingzone",
            name="type",
            field=models.CharField(
                choices=[
                    ("EXPENDED", "expended"),
                    ("OCEAN_SURFACE", "ocean"),
                    ("DRONE_SHIP", "ASDS"),
                    ("GROUND_PAD", "landing zone"),
                    ("PARACHUTE", "parachute"),
                    ("CATCH", "catch"),
                ],
                default="GROUND_PAD",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
