# Generated by Django 5.0.6 on 2024-08-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0068_landingzone_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="stageandrecovery",
            name="num_flights",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stageandrecovery",
            name="turnaround",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
