# Generated by Django 5.0.6 on 2024-08-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0069_stageandrecovery_num_flights_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stageandrecovery",
            name="turnaround",
        ),
        migrations.AddField(
            model_name="launch",
            name="company_turnaround",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="launch",
            name="pad_turnaround",
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="stageandrecovery",
            name="num_recoveries",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="stageandrecovery",
            name="stage_turnaround",
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="stageandrecovery",
            name="zone_turnaround",
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="stageandrecovery",
            name="num_flights",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
