# Generated by Django 5.0.6 on 2024-08-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0070_remove_stageandrecovery_turnaround_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spacecraftonlaunch",
            name="num_flights",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spacecraftonlaunch",
            name="spacecraft_turnaround",
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="spacecraftonlaunch",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
