# Generated by Django 5.0.6 on 2024-08-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0071_spacecraftonlaunch_num_flights_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="launch",
            name="company_turnaround",
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
