# Generated by Django 5.0.6 on 2024-08-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0072_alter_launch_company_turnaround"),
    ]

    operations = [
        migrations.AlterField(
            model_name="launch",
            name="company_turnaround",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="launch",
            name="pad_turnaround",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="spacecraftonlaunch",
            name="spacecraft_turnaround",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="stageandrecovery",
            name="stage_turnaround",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="stageandrecovery",
            name="zone_turnaround",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
