# Generated by Django 5.0.6 on 2024-08-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0073_alter_launch_company_turnaround_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="credit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="stage",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
