# Generated by Django 5.0.6 on 2024-08-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0074_stage_credit_alter_stage_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingzone",
            name="credit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pad",
            name="credit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="padused",
            name="credit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="spacecraft",
            name="credit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
