# Generated by Django 5.0.6 on 2024-08-20 04:06

from django.db import migrations, models


def replace_values(apps, schema_editor):
    FairingRecovery = apps.get_model("booster_tracker", "FairingRecovery")
    FairingRecovery.objects.filter(flights="Unknown").update(flights=None)
    FairingRecovery.objects.filter(flights="").update(flights=None)
    FairingRecovery.objects.filter(recovery="Unknown").update(recovery=None)
    FairingRecovery.objects.filter(recovery="").update(recovery=None)


class Migration(migrations.Migration):

    dependencies = [
        (
            "booster_tracker",
            "0075_landingzone_credit_pad_credit_padused_credit_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(replace_values),
        migrations.AlterField(
            model_name="fairingrecovery",
            name="flights",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fairingrecovery",
            name="recovery",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
