# Generated by Django 5.0.6 on 2024-08-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0076_alter_fairingrecovery_flights_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="launch",
            name="launch_photo",
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="launch",
            name="stages_string",
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
    ]
