# Generated by Django 5.0.6 on 2024-08-21 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0077_launch_launch_photo_launch_stages_string"),
    ]

    operations = [
        migrations.RenameField(
            model_name="launch",
            old_name="launch_photo",
            new_name="image",
        ),
    ]
