# Generated by Django 5.0.6 on 2024-08-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0078_rename_launch_photo_launch_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="launch",
            name="company_turnaround",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="launch",
            name="image",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="launch",
            name="stages_string",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
