# Generated by Django 5.0.6 on 2024-08-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "booster_tracker",
            "0079_alter_launch_company_turnaround_alter_launch_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fairingrecovery",
            name="recovery_attempt",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="launch",
            name="company_turnaround",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="launch",
            name="image",
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="launch",
            name="stages_string",
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="spacecraftonlaunch",
            name="num_flights",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
