# Generated by Django 5.0.6 on 2024-09-01 04:16

from django.db import migrations, models


def replace_values(apps, schema_editor):
    Launch = apps.get_model("booster_tracker", "Launch")

    for launch in Launch.objects.all():
        if "kg" in launch.mass:
            new_mass = int(
                float(
                    launch.mass.replace(" ", "")
                    .split("kg")[0]
                    .replace(",", "")
                    .replace("~", "")
                    .replace("–", "")
                    .replace("+", "")
                )
            )
            print(new_mass)
            launch.mass = new_mass
            launch.save()
        else:
            launch.mass = None
            launch.save()


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0080_fairingrecovery_recovery_attempt_and_more"),
    ]

    operations = [
        migrations.RunPython(replace_values),
        migrations.AlterField(
            model_name="launch",
            name="mass",
            field=models.IntegerField(blank=True, null=True, verbose_name="Mass (kg)"),
        ),
    ]
