# Generated by Django 5.0.6 on 2024-09-05 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0081_alter_launch_mass"),
    ]

    operations = [
        migrations.CreateModel(
            name="LaunchStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("significant", models.BooleanField()),
                ("string", models.CharField(max_length=400)),
                ("launch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="booster_tracker.launch")),
            ],
        ),
    ]
