# Generated by Django 5.0.6 on 2024-09-05 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0082_launchstats"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LaunchStats",
            new_name="LaunchStat",
        ),
    ]
