# Generated by Django 5.0.6 on 2024-09-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0083_rename_launchstats_launchstat"),
    ]

    operations = [
        migrations.AddField(
            model_name="launch",
            name="celery_task_id",
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
