# Generated by Django 5.0.6 on 2024-09-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0084_launch_celery_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="launch",
            name="x_post_sent",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
