# Generated by Django 5.0.6 on 2024-09-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0086_alter_launch_x_post_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="launch",
            name="x_post_sent",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
