# Generated by Django 5.0.6 on 2024-09-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0087_alter_launch_x_post_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="launch",
            name="exclude_from_missions",
            field=models.BooleanField(
                default=False, help_text="Exclude from mission number (Ex: Starship test missions)"
            ),
        ),
        migrations.AddField(
            model_name="launch",
            name="launch_precluded",
            field=models.BooleanField(default=False, help_text="Exclude from launch number (Ex: AMOS-6)"),
        ),
    ]
