# Generated by Django 5.0.6 on 2024-09-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0088_launch_exclude_from_missions_launch_launch_precluded"),
    ]

    operations = [
        migrations.AddField(
            model_name="rocket",
            name="image",
            field=models.ImageField(default="stage_photos/default_booster.jpg", upload_to="rocket_photos/"),
        ),
    ]
