# Generated by Django 5.0.6 on 2024-09-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0089_rocket_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="operator",
            name="image",
            field=models.ImageField(default="stage_photos/default_booster.jpg", upload_to="operator_photos/"),
        ),
        migrations.AddField(
            model_name="rocket",
            name="credit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
