# Generated by Django 5.0.6 on 2024-09-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0090_operator_image_rocket_credit"),
    ]

    operations = [
        migrations.AddField(
            model_name="operator",
            name="credit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
