# Generated by Django 5.0.6 on 2024-09-27 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0091_operator_credit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stageandrecovery",
            options={"ordering": ["id"], "verbose_name_plural": "Stage Recoveries"},
        ),
    ]
