# Generated by Django 5.0.6 on 2024-09-29 03:36

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0092_alter_stageandrecovery_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="pad",
            name="time_zone",
            field=timezone_field.fields.TimeZoneField(default="UTC", use_pytz=True),
            preserve_default=False,
        ),
    ]
