# Generated by Django 5.0.6 on 2024-09-29 03:38

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0093_pad_time_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pad",
            name="time_zone",
            field=timezone_field.fields.TimeZoneField(choices_display="WITH_GMT_OFFSET", use_pytz=True),
        ),
    ]
