# Generated by Django 5.0.6 on 2024-10-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0094_alter_pad_time_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="launch",
            name="launch_outcome",
            field=models.CharField(
                choices=[
                    ("SUCCESS", "success"),
                    ("FAILURE", "failure"),
                    ("PARTIAL FAILURE", "partial failure"),
                    ("TBD", "TBD"),
                ],
                default="TBD",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="stageandrecovery",
            name="method_success",
            field=models.CharField(
                choices=[("SUCCESS", "success"), ("FAILURE", "failure"), ("PRECLUDED", "precluded"), ("TBD", "TBD")],
                default="TBD",
                max_length=200,
            ),
        ),
    ]
