# Generated by Django 5.0.6 on 2025-02-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0095_alter_launch_launch_outcome_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingzone",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXPENDED", "expended"),
                    ("OCEAN_SURFACE", "ocean"),
                    ("DRONE_SHIP", "ASDS"),
                    ("GROUND_PAD", "landing zone"),
                    ("PARACHUTE", "parachute"),
                    ("CATCH", "catch"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
