# Generated by Django 5.0.6 on 2025-03-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0097_alter_landingzone_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="fairingrecovery",
            name="fairing_half",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="fairingrecovery",
            name="fairing_half2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
