# Generated by Django 5.0.6 on 2025-03-08 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0098_fairingrecovery_fairing_half_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fairingrecovery",
            name="fairing_half",
        ),
        migrations.RemoveField(
            model_name="fairingrecovery",
            name="fairing_half2",
        ),
    ]
