# Generated by Django 5.0.6 on 2025-04-27 23:44

from django.db import migrations, models
from booster_tracker.fetch_data import fetch_nxsf_launches


def replace_values(apps, schema_editor):
    Launch = apps.get_model("booster_tracker", "Launch")
    nxsf_launches = fetch_nxsf_launches()
    filtered_launches = [launch for launch in nxsf_launches if launch.get("l") == 1]
    launch_dict = {}
    for launch in filtered_launches:
        if launch.get("n"):
            launch_dict[launch["n"]] = launch
    for launch in Launch.objects.all():
        if launch.name in launch_dict:
            nxsf_id = launch_dict[launch.name].get("i")
            if launch.nxsf_id != nxsf_id:
                launch._from_task = True
                launch.nxsf_id = nxsf_id
                launch.save(update_fields=["nxsf_id"])
                launch._from_task = False


class Migration(migrations.Migration):

    dependencies = [
        ("booster_tracker", "0099_remove_fairingrecovery_fairing_half_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="launch",
            name="nxsf_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(replace_values),
    ]
