from django.urls import path
from booster_tracker import views
from booster_tracker.api_views import (
    LaunchOnlyApiView,
    LaunchApiView,
    RocketApiView,
    RocketFamilyApiView,
    OperatorApiView,
    OrbitApiView,
    PadApiView,
    PadInformationApiView,
    LandingZoneApiView,
    LandingZoneInformationApiView,
    StageAndRecoveryApiView,
    LaunchInformationApiView,
    StageApiView,
    StageInformationApiView,
    SpacecraftApiView,
    SpacecraftInformationApiView,
    BoatApiView,
    SpacecraftFamilyApiView,
    HomeDataApiView,
    FamilyInformationApiView,
    FilteredLaunchDaysApiView,
)

app_name = "booster_tracker"
urlpatterns = [
    # API Endpoints
    path("api/homedata/", HomeDataApiView.as_view()),
    path("api/launchesonly/", LaunchOnlyApiView.as_view()),
    path("api/launches/", LaunchApiView.as_view()),
    path("api/stages/", StageApiView.as_view()),
    path("api/stageinfo/", StageInformationApiView.as_view()),
    path("api/spacecraft/", SpacecraftApiView.as_view()),
    path("api/spacecraftfamilies/", SpacecraftFamilyApiView.as_view()),
    path("api/spacecraftinformation/", SpacecraftInformationApiView.as_view()),
    path("api/launchinfo/", LaunchInformationApiView.as_view()),
    path("api/rockets/", RocketApiView.as_view()),
    path("api/rocketfamilies/", RocketFamilyApiView.as_view()),
    path("api/familyinformation/", FamilyInformationApiView.as_view()),
    path("api/operators/", OperatorApiView.as_view()),
    path("api/orbit/", OrbitApiView.as_view()),
    path("api/pads/", PadApiView.as_view()),
    path("api/padinformation/", PadInformationApiView.as_view()),
    path("api/boats/", BoatApiView.as_view()),
    path("api/landingzones/", LandingZoneApiView.as_view()),
    path("api/landingzoneinformation/", LandingZoneInformationApiView.as_view()),
    path("api/stageandrecoveries/", StageAndRecoveryApiView.as_view()),
    path("api/calendarstats/", FilteredLaunchDaysApiView.as_view(), name="filter_calendar_stats"),
    # v1 views
    path("", views.home, name="home"),
    path("health/", views.health, name="health"),
    path("launches/<str:encoded_launch_name>/", views.launch_details, name="launch"),
    path("launches/", views.launches_list, name="launches"),
    path("dragons/<str:dragon_name>/", views.dragon_info, name="dragon"),
    path("dragons/", views.dragon_list, name="dragons"),
    path("starship/", views.starship_home, name="starship"),
    path(
        "<str:rocket_family>/<str:stage_type>/<str:stage_name>/",
        views.stage_info,
        name="stage",
    ),
    path("<str:rocket_family_name>/<str:stage_type>/", views.stage_list, name="stages"),
]
