from django.urls import path
from booster_tracker.api_views import (
    LaunchOnlyApiView,
    LaunchApiView,
    RocketApiView,
    RocketFamilyApiView,
    OperatorApiView,
    OrbitApiView,
    PadApiView,
    PadInformationApiView,
    LandingZoneApiView,
    LandingZoneInformationApiView,
    StageAndRecoveryApiView,
    LaunchInformationApiView,
    StageApiView,
    StageInformationApiView,
    SpacecraftApiView,
    SpacecraftInformationApiView,
    BoatApiView,
    SpacecraftFamilyApiView,
    HomeDataApiView,
    FamilyInformationApiView,
    FilteredLaunchDaysApiView,
    EDAApiView,
    AdditionalGraphsApiView,
)

from booster_tracker.views import compare_launch_times

app_name = "booster_tracker"
urlpatterns = [
    # API Endpoints
    path("homedata/", HomeDataApiView.as_view(), name="home"),
    path("launchesonly/", LaunchOnlyApiView.as_view(), name="launches_only"),
    path("launches/", LaunchApiView.as_view(), name="launches"),
    path("stages/", StageApiView.as_view(), name="stages"),
    path("stageinformation/", StageInformationApiView.as_view(), name="stage_information"),
    path("spacecraft/", SpacecraftApiView.as_view(), name="spacecraft"),
    path("spacecraftfamilies/", SpacecraftFamilyApiView.as_view(), name="spacecraft_families"),
    path("spacecraftinformation/", SpacecraftInformationApiView.as_view(), name="spacecraft_information"),
    path("launchinfo/", LaunchInformationApiView.as_view(), name="launch_information"),
    path("rockets/", RocketApiView.as_view(), name="rockets"),
    path("rocketfamilies/", RocketFamilyApiView.as_view(), name="rocket_families"),
    path("familyinformation/", FamilyInformationApiView.as_view(), name="family_information"),
    path("operators/", OperatorApiView.as_view(), name="operators"),
    path("orbit/", OrbitApiView.as_view(), name="orbit"),
    path("pads/", PadApiView.as_view(), name="pads"),
    path("padinformation/", PadInformationApiView.as_view(), name="pad_information"),
    path("boats/", BoatApiView.as_view(), name="boats"),
    path("landingzones/", LandingZoneApiView.as_view(), name="landing_zones"),
    path("landingzoneinformation/", LandingZoneInformationApiView.as_view(), name="landing_zone_information"),
    path("stageandrecoveries/", StageAndRecoveryApiView.as_view(), name="stage_and_recoveries"),
    path("calendarstats/", FilteredLaunchDaysApiView.as_view(), name="filter_calendar_stats"),
    path("edatable/", EDAApiView.as_view(), name="EDA table"),
    path("additional-graph-info/", AdditionalGraphsApiView.as_view(), name="additional graphs"),
    path("compare-launch-times/", compare_launch_times, name="compare_launch_times"),
]
